In [1]:
# devide samples into batches
# use of Dataloader class

import torch
import torchvision
from torch.utils.data import Dataset,DataLoader
import numpy as np
import math
import torch.nn as nn

In [2]:
data = np.array([1,2,3])

In [5]:
# factory returns an object
t1 = torch.Tensor(data)     #construcot calls
t2 = torch.tensor(data)     #factory
t3 = torch.as_tensor(data)  #factory
t4 = torch.from_numpy(data) #factory

#factories have more doccumentation an better to use

In [6]:
#data types

print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [7]:
#explicitly typecasting tensor type

torch.tensor(np.array([1,2,3]), dtype=torch.float32)

tensor([1., 2., 3.])

In [8]:
data[0] = 0 
data[1] = 0
data[2] = 0

In [10]:
print(t1)
print(t2)
print(t3)
print(t4)

#so as tensor and from numpy is changed, but not the constructor and default factory
# but in the case of t3 and t4, memory is being shared by referring to the same object


tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
