In [1]:
# Reshaping operations
# Element-wise operation
# reduction operation
# access operation

import torch
import torchvision
from torch.utils.data import Dataset,DataLoader
import numpy as np
import math
import torch.nn as nn

In [2]:
# 3x4 tensor
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [3]:
t.size()

torch.Size([3, 4])

In [4]:
t.shape

torch.Size([3, 4])

In [5]:
len(t.shape)

2

In [7]:
torch.tensor(t.shape).prod() # number of componen

tensor(12)

In [9]:
t.numel() # number of elements

12

In [10]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [11]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [12]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [13]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [14]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [15]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [20]:
def flaten(t):
    t = t.reshape(1,-1) # -1 in tensor is always used to tell the machine to determine the value.
                        # if a 3x4 tensor in given, then -1 will deciede that it's 12
    t = t.squeeze()
    return t

In [21]:
flaten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [22]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])