In [1]:
import torch
import torchvision
from torch.utils.data import Dataset,DataLoader
import numpy as np
import math
import torch.nn as nn

In [3]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [4,6],
    [7,8]
], dtype=torch.float32)

In [4]:
t1[0]

tensor([1., 2.])

In [5]:
t1[0][0]

tensor(1.)

In [7]:
# element wise means operation on t1[0][0] and t2[0][0]
# or operation on t1[1][1] and t2[1][1]

t1[0][0]

tensor(1.)

In [9]:
t2[0][0]

tensor(4.)

In [11]:
t1 + t2 #element wise operation. also other - * /

tensor([[ 5.,  8.],
        [10., 12.]])

In [12]:
# add, devide with single scaler value

t1.add(2) # first converted automatically to 2x2 then adding

# this is called broadcasting, works with other arithmatics too

tensor([[3., 4.],
        [5., 6.]])

In [13]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [4,6]
], dtype=torch.float32)

In [20]:
# will it work? YES, broadcasting is done in the background
t1 + t2 

tensor([[ 5.,  8.],
        [ 7., 10.]])