In [ ]:
import torch
import torchvision
from torch.utils.data import Dataset,DataLoader
import numpy as np
import math
import torch.nn as nn

# use of reduction operations

In [19]:
# reduces number of elements in a logical way

t = torch.tensor([
    [1,2,1],
    [0,1,0]
], dtype=torch.float32)

In [20]:
t.sum()

tensor(5.)

In [21]:
t.numel()

6

In [22]:
t.sum().numel()

1

In [23]:
t.sum().numel() < t.numel()

True

In [24]:
# sum reduces the element size
# Some other examples of reduction

t.sum()

tensor(5.)

In [25]:
t.prod()

tensor(0.)

In [26]:
t.mean()

tensor(0.8333)

In [27]:
t.std()

tensor(0.7528)

In [28]:
# dimentin 0 is columns wise and dimension 1 is row wise
t1 = torch.tensor([
    [2,2,1],
    [1,2,1],
    [1,2,3]
], dtype=torch.float32)

In [29]:
t1.sum(dim=0)

tensor([4., 6., 5.])

In [30]:
t1.sum(dim=1)

tensor([5., 4., 6.])

# use of argMax

In [37]:
# which is the maximum among the tensor

t2 = torch.tensor([
    [2,2,5],
    [1,2,1],
    [1,2,3]
], dtype=torch.float32)

# return the index
t2.argmax()

tensor(2)

In [38]:
t2.max(axis=0) #returns indices as well as values

torch.return_types.max(
values=tensor([2., 2., 5.]),
indices=tensor([0, 0, 0]))

In [39]:
# in convention used in dimension 1
t2.argmax(dim=1)

tensor([2, 1, 2])

In [41]:
t.mean(dim=0).tolist()

[0.5, 1.5, 0.5]